# Generated by Django 4.1.7 on 2023-08-20 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("karaoke", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointmodel",
            name="duedate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
